from kivy.app import App
from kivy.properties import ObjectProperty
from kivy.network.urlrequest import UrlRequest
from kivy.uix.screenmanager import ScreenManager, Screen

from client.client_config import ClientConfig


class MyScreenManager(ScreenManager):
    pass


class SimpleScreen(Screen):
    client_config = ClientConfig()
    # Placeholder for label generated by .kv file
    status_label = ObjectProperty(None)

    def heartbeat_request(self, *args):
        UrlRequest(self.client_config.SERVER_URL, self.handle_heartbeat)

    def handle_heartbeat(self, req, result):
        self.status_label.text = str("Last Heartbeat: " + str(result))


class SimpleClientApp(App):
    def build(self):
        return MyScreenManager()


if __name__ == "__main__":
    SimpleClientApp().run()
