"""Add annotations column to annotations entity

Revision ID: 47e017381b60
Revises: eae3bc9276bb
Create Date: 2020-06-15 15:33:34.746864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47e017381b60'
down_revision = 'eae3bc9276bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('annotations', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'annotations')
    # ### end Alembic commands ###
