"""annotations: rename annotations column to coco

Revision ID: d5024e33d215
Revises: 47e017381b60
Create Date: 2020-06-15 15:35:00.193348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5024e33d215'
down_revision = '47e017381b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('coco', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.drop_column('annotations', 'annotations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('annotations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('annotations', 'coco')
    # ### end Alembic commands ###
