version: "3"
services:
  db:
    image: "postgres:12"
    container_name: "annotations-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
