#:import utils kivy.utils
#:import ClientConfig client.client_config.ClientConfig

<Alert>:
    size_hint: None, None
    size: app.root.width/3, app.root.height/3
    auto_dismiss: True
    alert_message: ''
    BoxLayout:
        orientation: 'vertical'
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            Label:
                text: root.alert_message
                size_hint_y: None
                height: self.texture_size[1]
                text_size: self.width, None
        AnchorLayout:
            anchor_x: 'center'
            anchor_y: 'bottom'
            size_hint: (1, 0.2)
            Button:
                size_hint_x: 0.3
                text: 'Ok'
                on_release: root.dismiss()


<LabelInput@BoxLayout>:
    orientation: 'horizontal'
    default_text: 'default'
    label_text: 'default label'
    text_field: text_field
    Label:
        text: root.label_text
    TextInput:
        id: text_field
        text: root.default_text

<TileView>:
    tile_width: 0
    tile_height: 0
    size_hint_y: None
    height: self.minimum_height
    col_default_width: root.tile_width
    col_force_default: True
    row_default_height: root.tile_height
    row_force_default: True
    spacing: 16
    padding: 16
    cols: int((self.width - self.padding[0]) / (self.col_default_width + self.spacing[0]))

<NumericInput>:
    decimal_places: 2
    text_input: text_input
    TextInput:
        id: text_input
        size_hint_x: None
        width: root.width - 20
        text: str(root.value)
        multiline: False
        halign: 'center'
        valign: 'center'
        on_text_validate: root.validate_user_input()
    BoxLayout:
        size_hint_x: None
        width: 20
        orientation: 'vertical'
        padding: 1
        Button:
            text: '+'
            disabled: root.value >= root.max
            on_release:
                root.value = round(min(root.value + root.step, root.max), root.decimal_places)
        Button:
            text: '-'
            disabled: root.value <= root.min
            on_release:
                root.value = round(max(root.value - root.step, root.min), root.decimal_places)

<PaintWindow>
    mask_layer: mask_layer
    fbo: self.fbo
    mask_color: self.mask_color
    EffectWidget:
        size: root.size
        effects: [common.TransparentBlackEffect()]
        Widget:
            size: root.size
            id: mask_layer
            canvas:
                Color:
                    rgba: root.mask_color