<ProjectToolScreen>:
    BoxLayout:
        orientation: "vertical"
        ActionBar:
            pos_hint: {'top':1}
            ActionView:
                use_separator: True
                ActionPrevious:
                    title: app.current_project_name
                    with_previous: True
                    on_release: app.show_home()
                ActionButton:
                    text: "Edit"
                    on_release: print("Edit Project")
                ActionButton:
                    text: "Delete"
                    on_release: print("Delete Project")
        TileView:
            tile_width: 150
            tile_height: 150
            padding: 32
            spacing: 32
            Button:
                text: "Add Images"
                on_release: root.upload_images()
            Button:
                text: "View Images"
                on_release: app.show_image_viewer()
            Button:
                text: "Instance Annotator"
                on_release: app.open_instance_annotator()