<DeleteProjectPopup>:
    size_hint: None, None
    size: app.root.width/2, app.root.height/2
    auto_dismiss: True
    title: "Delete Project"
    message: ""
    confirmation_callback: None
    BoxLayout:
        padding: 8
        spacing: 8
        orientation: 'vertical'
        Label:
            text: root.message
        AnchorLayout:
            anchor_x: 'center'
            anchor_y: 'bottom'
            BoxLayout:
                orientation: 'horizontal'
                padding: 8
                spacing: 8
                Button:
                    size_hint: (0.3, 0.2)
                    text: 'Delete'
                    on_release: root.confirmation_callback(); root.dismiss()
                Button:
                    size_hint: (0.3, 0.2)
                    text: 'Cancel'
                    on_release: root.dismiss()

<AddProjectPopup>:
    size_hint: None, None
    size: app.root.width/2, app.root.height/2
    auto_dismiss: False
    title: "Add New Project"
    BoxLayout:
        padding: 8
        spacing: 8
        orientation: 'vertical'
        LabelInput:
            id: project_name
            size_hint_y: 0.2
            label_text: "Project Name"
        AnchorLayout:
            anchor_x: 'center'
            anchor_y: 'bottom'
            BoxLayout:
                orientation: 'horizontal'
                padding: 8
                spacing: 8
                Button:
                    size_hint: (0.3, 0.2)
                    text: 'Add'
                    on_release: root.add_project(project_name=project_name.text_field.text)
                Button:
                    size_hint: (0.3, 0.2)
                    text: 'Cancel'
                    on_release: root.dismiss()

<ControlBar>:
    orientation: "horizontal"
    size_hint_y: None
    width: root.width
    height: 64
    padding: (16, 16, 16, 8)
    spacing: 16
    Button:
        size_hint_x: None
        width: 150
        text: "Add"
        on_release: root.open_add_project_popup()
    Button:
        id: btn_refresh_project
        size_hint_x: None
        width: 150
        text: "Refresh"
        on_release: root.trigger_project_refresh()

<ProjectCard>:
    project_name: self.project_name
    project_id: self.project_id
    image: self.image
    total_images: self.total_images
    labeled_images: self.labeled_images
    last_update_time: self.last_update_time
    last_update_label: last_update_label
    FloatLayout:
        BoxLayout:
            pos_hint:{"x": 0.00, "y": 0.00}
            orientation: "vertical"
            canvas:
                Color:
                    rgba: 1, 0, 0, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            BoxLayout:
                Label:
                    text: root.image
            BoxLayout:
                size_hint: (1, 0.3)
                Label:
                    text: root.project_name
            ProgressBar:
                max: root.total_images
                value: root.labeled_images
                size_hint: (1, 0.15)
            Label:
                id: last_update_label
                size_hint: (1, 0.2)
                markup: True
                font_size: "13dp"
                text: "Updated [b][color=3AD6E7]5 minutes[/color][/b] ago"
        Button:
            pos_hint:{"x": 0.9, "y": 0.9}
            size_hint: (0.1, 0.1)
            text: "X"
            on_release: root.confirm_delete_project()

<ProjectViewWindow>:
    tile_width: 150
    tile_height: 200


<ProjectSelectScreen>:
    control_bar: control_bar
    project_view_window: project_view_window
    BoxLayout:
        orientation: "vertical"
        ActionBar:
            pos_hint: {'top':1}
            ActionView:
                use_separator: True
                ActionPrevious:
                    title: 'Select a Project'
                    with_previous: False
        ControlBar:
            id: control_bar
        ProjectViewWindow:
            id: project_view_window