<ControlBar>:
    orientation: "horizontal"
    size_hint_y: None
    width: root.width
    height: 64
    padding: (16, 16, 16, 8)
    spacing: 16
    Button:
        size_hint_x: None
        width: 150
        text: "Add"
    Button:
        size_hint_x: None
        width: 150
        text: "Delete"
    Button:
        id: btn_refresh_project
        size_hint_x: None
        width: 150
        text: "Refresh"
        on_press: root.trigger_project_refresh()

<ProjectCard>:
    title: self.title
    image: self.image
    orientation: "vertical"
    spacing: 16
    BoxLayout:
        canvas:
            Color:
                rgba: 1, 0, 0, 1
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            text: root.image

    BoxLayout:
        size_hint: (1, 0.35)
        canvas:
            Color:
                rgba: 1, 0, 0, 1
            Rectangle:
                pos: self.pos
                size: self.size
        Label:

            text: root.title

<ProjectViewWindow>:
    col_default_width: 150
    col_force_default: True
    row_default_height: 200
    row_force_default: True

    spacing: 16
    padding: (16, 8, 16, 16)
    cols: int((self.width - self.padding[0]) / (150 + self.spacing[0]))

<ProjectScreen>:
    control_bar: control_bar
    project_view_window: project_view_window
    BoxLayout:
        orientation: "vertical"
        ActionBar:
            pos_hint: {'top':1}
            ActionView:
                use_separator: True
                ActionPrevious:
                    title: 'Example App'
                    with_previous: False
        ControlBar:
            id: control_bar
        ProjectViewWindow:
            id: project_view_window